### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by vmitchell85**
This PR adds instructions on publishing the config file and assets.

### CODE REVIEW

**Comment by AndreasElia** [comment]
Hey @vmitchell85, thanks for the PR.

I believe the install command publishes these assets already. Would you prefer we removed the install command in turn for the artisan `vendor:publish` publishing?

**Comment by vmitchell85** [comment]
Hmm... thought I ran that... let me wipe and reinstall...

**Comment by vmitchell85** [comment]
Worked that time.. nevermind... sorry.

**Comment by AndreasElia** [comment]
No worries at all @vmitchell85, I think I may be in favour of ditching the command in favour for publishing them as in this PR as it's also less maintenance and code within the package. I'll sort it out sometime tonight unless you'd like to submit a PR to remove it and update the documentation.

**Comment by vmitchell85** [comment]
I'm a little busy working on a project for a client, but if I have time I might submit a PR.

**Pull request closed without merging**
