### PR TITLE
Add Laravel Nova Dashboard and Metrics

### PR DESCRIPTION
**Pull request by andreascreten**
### Added

- Added a dashboard for Laravel Nova
- Added PageView metric for Laravel Nova
- Added UniqueUsers metric for Laravel Nova
- Added Devices metric for Laravel Nova

---
This is what the dashboard looks like:

Screenshot 2023-03-04 at 00 17 31

### CODE REVIEW

**Comment by andreaselia** [comment]
Thanks for your PR @andreascreten. I'm not sure if it makes sense to have this as part of the main package vs having it as a nova-laravel-analytics package similar to what I did with Filament here?

https://github.com/andreaselia/filament-laravel-analytics

**Comment by andreaselia** [comment]
> Any reason to do it in a separate package? It does not sit in the way of anything else.

Thinking more to keep this as a lightweight package with a simple focus. Do you feel like it shouldn't be a separate package?

**Comment by andreascreten** [comment]
I think the overhead is minimal and the ease of use is more important to me.

**Comment by andreaselia** [comment]
I'm on the fence here. On one hand I see your point, but on the other it would also be easy to include a nova-laravel-analytics package that depends on this one for abstraction. Where would we draw the line on including Nova, then merging Filament into this, and then anything else that may come?

I guess it's not much overhead as you said, and they are in their own namespace which keeps it maintainable, so I have no issues with your implementation. I'll sleep on this tonight and check in again tomorrow, hope that's okay @andreascreten.

@tomirons what are your thoughts on this?

**Comment by andreascreten** [comment]
Sure, no worries! It is not a biggy to extract it anyway.

**Comment by andreaselia** [comment]
> Sure, no worries! It is not a biggy to extract it anyway.

Just going to wait until @tomirons is around before making a final decision on this, hope you're having a good weekend so far!

**Comment by andreaselia** [comment]
Thanks again @andreascreten for your PR, and @tomirons for taking a look and pushing me off the fence I was sitting on and merging it 😁

**Comment by andreascreten** [comment]
Awesome. I will maybe add some more metrics in the future.

**Pull request merged**
