### PR TITLE
Add support for ignoring columns in the database

### PR DESCRIPTION
**Pull request by grantholle**
This adds support to ignore some columns when saving the page view record, i.e. ignoring the `host` column since I have a single tenant app and don't need it to bloat the table.

I also changed the test function names to get rid of the deprecation warning about metadata.

### CODE REVIEW

**Comment by andreaselia** [comment]
Hey @grantholle, thanks for your PR. I'll try and take a proper look and test things out over the weekend.

Would you mind reverting the test names to keep the `/** @test */` way of doing things rather than `test_` please? Alternatively we could roll with the `#[Test]` attribute since I believe from the Laravel 11 requirements we can do that.

**Comment by grantholle** [comment]
I would going to use the `#[Test]` attribute, but then the package would have to drop support for php 7.4, as it's an 8.0 feature.

**Comment by andreaselia** [comment]
We can drop support for PHP 7.4, that works for me.

**Comment by grantholle** [comment]
Yeah I agree. Since v2.0.0 is already tagged and is php ^8.0, might as well just go with that major version. I think you can still support the older versions of Laravel, but just bump the php requirement.

**Comment by grantholle** [comment]
Ok @andreaselia, should be all set now

**Review by tomirons — APPROVED** [review]

**Comment by andreaselia** [comment]
Thanks @grantholle, apologies about the delay.

**Pull request merged**
